/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRentalConditionsRouteImport } from './routes/legal.rental-conditions'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as CarsCountryRouteImport } from './routes/cars.$country'
import { Route as CarsCountryCityRouteImport } from './routes/cars.$country.$city'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRentalConditionsRoute = LegalRentalConditionsRouteImport.update({
  id: '/rental-conditions',
  path: '/rental-conditions',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const CarsCountryRoute = CarsCountryRouteImport.update({
  id: '/cars/$country',
  path: '/cars/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCountryCityRoute = CarsCountryCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => CarsCountryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cars/$country': typeof CarsCountryRouteWithChildren
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/rental-conditions': typeof LegalRentalConditionsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/cars/$country/$city': typeof CarsCountryCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cars/$country': typeof CarsCountryRouteWithChildren
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/rental-conditions': typeof LegalRentalConditionsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/cars/$country/$city': typeof CarsCountryCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cars/$country': typeof CarsCountryRouteWithChildren
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/rental-conditions': typeof LegalRentalConditionsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/cars/$country/$city': typeof CarsCountryCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/results'
    | '/sitemap.xml'
    | '/cars/$country'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/rental-conditions'
    | '/legal/terms'
    | '/cars/$country/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/results'
    | '/sitemap.xml'
    | '/cars/$country'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/rental-conditions'
    | '/legal/terms'
    | '/cars/$country/$city'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/results'
    | '/sitemap.xml'
    | '/cars/$country'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/rental-conditions'
    | '/legal/terms'
    | '/cars/$country/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CarsCountryRoute: typeof CarsCountryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/rental-conditions': {
      id: '/legal/rental-conditions'
      path: '/rental-conditions'
      fullPath: '/legal/rental-conditions'
      preLoaderRoute: typeof LegalRentalConditionsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/cars/$country': {
      id: '/cars/$country'
      path: '/cars/$country'
      fullPath: '/cars/$country'
      preLoaderRoute: typeof CarsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$country/$city': {
      id: '/cars/$country/$city'
      path: '/$city'
      fullPath: '/cars/$country/$city'
      preLoaderRoute: typeof CarsCountryCityRouteImport
      parentRoute: typeof CarsCountryRoute
    }
  }
}

interface LegalRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalRentalConditionsRoute: typeof LegalRentalConditionsRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalRentalConditionsRoute: LegalRentalConditionsRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface CarsCountryRouteChildren {
  CarsCountryCityRoute: typeof CarsCountryCityRoute
}

const CarsCountryRouteChildren: CarsCountryRouteChildren = {
  CarsCountryCityRoute: CarsCountryCityRoute,
}

const CarsCountryRouteWithChildren = CarsCountryRoute._addFileChildren(
  CarsCountryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRouteWithChildren,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CarsCountryRoute: CarsCountryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
