export const TELNYX_CONFIG_KEYS = {
  API_KEY: "TELNYX_API_KEY",
  PUBLIC_KEY: "TELNYX_PUBLIC_KEY",
  CONNECTION_ID: "TELNYX_CONNECTION_ID",
  DEFAULT_FROM_NUMBER: "TELNYX_DEFAULT_FROM_NUMBER",
  WEBHOOK_SIGNATURE_REQUIRED: "TELNYX_WEBHOOK_SIGNATURE_REQUIRED",
  WEBHOOK_IP_ALLOWLIST: "TELNYX_WEBHOOK_IP_ALLOWLIST",
  WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS: "TELNYX_WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS",
} as const;
