export const VONAGE_ENV_KEYS = {
  API_KEY: "VONAGE_API_KEY",
  API_SECRET: "VONAGE_API_SECRET",
  APPLICATION_ID: "VONAGE_APPLICATION_ID",
  PRIVATE_KEY_PATH: "VONAGE_PRIVATE_KEY_PATH",
  BASE_URL: "VONAGE_BASE_URL",
  DEFAULT_FROM_NUMBER: "VONAGE_DEFAULT_FROM_NUMBER",
} as const;

export const PUBLIC_API_BASE_URL_KEY = "PUBLIC_API_BASE_URL";

export { VONAGE_WEBHOOK_ENV_KEYS } from "./vonage-webhook.constants";
