/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProvidersRouteImport } from './routes/app.providers'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppCallsRouteImport } from './routes/app.calls'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppLeadsLeadIdRouteImport } from './routes/app.leads.$leadId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calls': typeof AppCallsRoute
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calls': typeof AppCallsRoute
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calls': typeof AppCallsRoute
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/booking'
    | '/confirmation'
    | '/payment'
    | '/search'
    | '/app/admin'
    | '/app/analytics'
    | '/app/bookings'
    | '/app/calls'
    | '/app/leads'
    | '/app/notifications'
    | '/app/payments'
    | '/app/providers'
    | '/app/settings'
    | '/app/team'
    | '/app/'
    | '/app/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/confirmation'
    | '/payment'
    | '/search'
    | '/app/admin'
    | '/app/analytics'
    | '/app/bookings'
    | '/app/calls'
    | '/app/leads'
    | '/app/notifications'
    | '/app/payments'
    | '/app/providers'
    | '/app/settings'
    | '/app/team'
    | '/app'
    | '/app/leads/$leadId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/booking'
    | '/confirmation'
    | '/payment'
    | '/search'
    | '/app/admin'
    | '/app/analytics'
    | '/app/bookings'
    | '/app/calls'
    | '/app/leads'
    | '/app/notifications'
    | '/app/payments'
    | '/app/providers'
    | '/app/settings'
    | '/app/team'
    | '/app/'
    | '/app/leads/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BookingRoute: typeof BookingRoute
  ConfirmationRoute: typeof ConfirmationRoute
  PaymentRoute: typeof PaymentRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls': {
      id: '/app/calls'
      path: '/calls'
      fullPath: '/app/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/$leadId': {
      id: '/app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/app/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
  }
}

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppCallsRoute: typeof AppCallsRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppCallsRoute: AppCallsRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BookingRoute: BookingRoute,
  ConfirmationRoute: ConfirmationRoute,
  PaymentRoute: PaymentRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
